plot(time_tick1,price1,'k-');
hold on;
plot(time_tick2,price2,'b-');
hold on;
plot(time_tick3,price3,'r-');
hold on;
plot(time_tick4,price4,'g-');
hold on;
plot(time_tick5,price5,'k:');
hold on;
plot(time_tick6,price6,'b:');
hold on;
plot(time_tick7,price7,'r:');
hold on;
plot(time_tick8,price8,'g:');
hold on;
plot(time_tick9,price9,'y-');
hold on;
plot(time_tick10,price10,'y:');
legend('price1','price2','price3','price4','price5','price6','price7','price8','price9','price10');