plot(time_tick1,volume1,'k-');
hold on;
plot(time_tick2,volume2,'b-');
hold on;
plot(time_tick3,volume3,'r-');
hold on;
plot(time_tick4,volume4,'g-');
hold on;
plot(time_tick5,volume5,'k:');
hold on;
plot(time_tick6,volume6,'b:');
hold on;
plot(time_tick7,volume7,'r:');
hold on;
plot(time_tick8,volume8,'g:');
hold on;
plot(time_tick9,volume9,'y-');
hold on;
plot(time_tick10,volume10,'y:');
legend('volume1','volume2','volume3','volume4','volume5','volume6','volume7','volume8','volume9','volume10');